export type Language = 'en' | 'id';

export const translations = {
  en: {
    // Header
    appName: 'ClearContract',
    securePrivate: 'Secure & Private',
    
    // Language switcher
    english: 'English',
    indonesian: 'Bahasa Indonesia',
    
    // Hero section
    badge: 'AI-Powered Contract Analysis',
    heroTitle: 'Understand Your Contracts',
    heroTitleHighlight: 'In Plain English',
    heroDescription: "Upload any legal contract and get an instant AI analysis that highlights red flags, hidden fees, and problematic clauses — explained like you're talking to a friend.",
    
    // Upload zone
    uploadPdf: 'Upload PDF',
    pasteText: 'Paste Text',
    dragDrop: 'Drag & drop your contract',
    dropHere: 'Drop your contract here',
    clickBrowse: 'or click to browse (PDF up to 10MB)',
    pasteTextPlaceholder: 'Paste your contract text here... (minimum 100 characters)',
    characters: 'characters',
    minimum: 'minimum 100',
    remove: 'Remove',
    analyzeContract: 'Analyze Contract',
    analyzing: 'Analyzing...',
    privacyNote: 'Your contract is processed securely and never stored on our servers.',
    
    // Features
    instantAnalysis: 'Instant Analysis',
    instantAnalysisDesc: 'Get results in seconds, not hours',
    redFlagDetection: 'Red Flag Detection',
    redFlagDetectionDesc: 'Identify problematic clauses automatically',
    privacyFirst: 'Privacy First',
    privacyFirstDesc: 'Your documents are never stored',
    
    // What we look for
    whatWeLookFor: 'What we look for',
    unreasonablePenalties: 'Unreasonable penalties',
    hiddenFees: 'Hidden fees & auto-renewals',
    privacyViolations: 'Privacy violations',
    oneSidedLiability: 'One-sided liability clauses',
    nonCompete: 'Non-compete restrictions',
    waivedRights: 'Rights you may be waiving',
    
    // Loading state
    extractingText: 'Extracting Contract Text...',
    extractingDesc: 'Reading and extracting text from your document',
    analyzingContract: 'Analyzing Contract...',
    analyzingDesc: 'Our AI is carefully reviewing your contract for potential issues',
    extractStep: 'Extract text from document',
    analyzeStep: 'Analyze for red flags',
    generateStep: 'Generate report',
    done: 'Done',
    analysisTime: 'Analysis typically takes 15-30 seconds depending on contract length',
    
    // Results
    analyzeAnother: 'Analyze Another',
    analysisComplete: 'Contract Analysis Complete',
    riskHigh: 'This contract has significant concerns that need attention.',
    riskMedium: 'This contract has some areas worth reviewing carefully.',
    riskLow: 'This contract appears relatively fair and standard.',
    summary: 'Summary',
    highRisk: 'High Risk',
    mediumRisk: 'Medium Risk',
    lowRisk: 'Low Risk',
    noRedFlags: 'No red flags found',
    redFlags: 'Red Flags',
    fromContract: 'From the contract:',
    positiveAspects: 'Positive Aspects',
    disclaimer: 'This analysis is generated by AI and should not be considered legal advice. Please consult with a qualified attorney for professional legal guidance.',
    
    // Footer
    footerDisclaimer: 'ClearContract provides AI-generated insights and is not a substitute for legal advice.',
    
    // Errors
    noFileUploaded: 'No file uploaded',
    onlyPdfSupported: 'Only PDF files are supported',
    fileTooLarge: 'File size exceeds 10MB limit',
    extractionFailed: 'Failed to extract text from PDF. Please try again.',
    invalidPdf: 'The file appears to be corrupted or is not a valid PDF',
    noTextExtracted: 'Could not extract text from PDF. The file may be scanned/image-based or empty.',
    analysisFailed: 'Failed to analyze contract. Please try again.',
    textTooShort: 'Contract text is too short to analyze. Please provide more content.',
    
    // Toast messages
    extractSuccess: 'Text extracted successfully',
    pagesProcessed: 'page(s) processed',
    analysisCompleteToast: 'Analysis complete!',
    potentialIssues: 'potential issue(s) to review',
    extractionFailedToast: 'Extraction failed',
    analysisFailedToast: 'Analysis failed',
    
    // Enhanced error messages
    networkError: 'Network connection failed. Please check your internet connection.',
    timeoutError: 'Request timed out. Please try again.',
    serverError: 'Server error occurred. Please try again later.',
    rateLimitError: 'Too many requests. Please wait a moment and try again.',
    apiKeyError: 'Service configuration error. Please contact support.',
    safetyFilterError: 'Content was flagged by safety filters. Please try different content.',
    unknownError: 'An unexpected error occurred. Please try again.',
    
    // Retry messages
    retrying: 'Retrying...',
    retryAttempt: 'Retry attempt',
    of: 'of',
    tryAgain: 'Try Again',
    
    // Export
    exportJson: 'Export JSON',
    exportPdf: 'Export PDF',
    exportSuccess: 'Export successful',
    downloadStarted: 'Download started',
    generatedAt: 'Generated at',
    
    // History
    recentAnalyses: 'Recent Analyses',
    noHistory: 'No analysis history yet',
    viewDetails: 'View Details',
    clearHistory: 'Clear History',
    historyClearedToast: 'History cleared',
    analysisRestored: 'Analysis restored',
    deleteFromHistory: 'Delete',
    ago: 'ago',
    justNow: 'Just now',
    minute: 'minute',
    minutes: 'minutes',
    hour: 'hour',
    hours: 'hours',
    day: 'day',
    days: 'days',
  },
  
  id: {
    // Header
    appName: 'ClearContract',
    securePrivate: 'Aman & Privat',
    
    // Language switcher
    english: 'English',
    indonesian: 'Bahasa Indonesia',
    
    // Hero section
    badge: 'Analisis Kontrak Berbasis AI',
    heroTitle: 'Pahami Kontrak Anda',
    heroTitleHighlight: 'Dengan Bahasa Sederhana',
    heroDescription: 'Unggah kontrak hukum apa pun dan dapatkan analisis AI instan yang menyoroti tanda bahaya, biaya tersembunyi, dan klausul bermasalah — dijelaskan dengan bahasa yang mudah dipahami.',
    
    // Upload zone
    uploadPdf: 'Unggah PDF',
    pasteText: 'Tempel Teks',
    dragDrop: 'Seret & lepas kontrak Anda',
    dropHere: 'Lepaskan kontrak Anda di sini',
    clickBrowse: 'atau klik untuk memilih file (PDF maks 10MB)',
    pasteTextPlaceholder: 'Tempel teks kontrak Anda di sini... (minimal 100 karakter)',
    characters: 'karakter',
    minimum: 'minimal 100',
    remove: 'Hapus',
    analyzeContract: 'Analisis Kontrak',
    analyzing: 'Menganalisis...',
    privacyNote: 'Kontrak Anda diproses dengan aman dan tidak pernah disimpan di server kami.',
    
    // Features
    instantAnalysis: 'Analisis Instan',
    instantAnalysisDesc: 'Hasil dalam hitungan detik',
    redFlagDetection: 'Deteksi Tanda Bahaya',
    redFlagDetectionDesc: 'Identifikasi klausul bermasalah secara otomatis',
    privacyFirst: 'Privasi Utama',
    privacyFirstDesc: 'Dokumen Anda tidak pernah disimpan',
    
    // What we look for
    whatWeLookFor: 'Yang kami cari',
    unreasonablePenalties: 'Penalti yang tidak wajar',
    hiddenFees: 'Biaya tersembunyi & perpanjangan otomatis',
    privacyViolations: 'Pelanggaran privasi',
    oneSidedLiability: 'Klausul tanggung jawab sepihak',
    nonCompete: 'Pembatasan non-kompetisi',
    waivedRights: 'Hak yang mungkin Anda lepaskan',
    
    // Loading state
    extractingText: 'Mengekstrak Teks Kontrak...',
    extractingDesc: 'Membaca dan mengekstrak teks dari dokumen Anda',
    analyzingContract: 'Menganalisis Kontrak...',
    analyzingDesc: 'AI kami sedang meninjau kontrak Anda dengan cermat untuk potensi masalah',
    extractStep: 'Ekstrak teks dari dokumen',
    analyzeStep: 'Analisis tanda bahaya',
    generateStep: 'Buat laporan',
    done: 'Selesai',
    analysisTime: 'Analisis biasanya memakan waktu 15-30 detik tergantung panjang kontrak',
    
    // Results
    analyzeAnother: 'Analisis Lainnya',
    analysisComplete: 'Analisis Kontrak Selesai',
    riskHigh: 'Kontrak ini memiliki masalah signifikan yang perlu diperhatikan.',
    riskMedium: 'Kontrak ini memiliki beberapa area yang perlu ditinjau dengan cermat.',
    riskLow: 'Kontrak ini tampak cukup adil dan standar.',
    summary: 'Ringkasan',
    highRisk: 'Risiko Tinggi',
    mediumRisk: 'Risiko Sedang',
    lowRisk: 'Risiko Rendah',
    noRedFlags: 'Tidak ditemukan tanda bahaya',
    redFlags: 'Tanda Bahaya',
    fromContract: 'Dari kontrak:',
    positiveAspects: 'Aspek Positif',
    disclaimer: 'Analisis ini dihasilkan oleh AI dan tidak boleh dianggap sebagai nasihat hukum. Silakan konsultasikan dengan pengacara yang berkualifikasi untuk panduan hukum profesional.',
    
    // Footer
    footerDisclaimer: 'ClearContract menyediakan wawasan yang dihasilkan AI dan bukan pengganti nasihat hukum.',
    
    // Errors
    noFileUploaded: 'Tidak ada file yang diunggah',
    onlyPdfSupported: 'Hanya file PDF yang didukung',
    fileTooLarge: 'Ukuran file melebihi batas 10MB',
    extractionFailed: 'Gagal mengekstrak teks dari PDF. Silakan coba lagi.',
    invalidPdf: 'File tampaknya rusak atau bukan PDF yang valid',
    noTextExtracted: 'Tidak dapat mengekstrak teks dari PDF. File mungkin berupa gambar/scan atau kosong.',
    analysisFailed: 'Gagal menganalisis kontrak. Silakan coba lagi.',
    textTooShort: 'Teks kontrak terlalu pendek untuk dianalisis. Mohon berikan lebih banyak konten.',
    
    // Toast messages
    extractSuccess: 'Teks berhasil diekstrak',
    pagesProcessed: 'halaman diproses',
    analysisCompleteToast: 'Analisis selesai!',
    potentialIssues: 'potensi masalah untuk ditinjau',
    extractionFailedToast: 'Ekstraksi gagal',
    analysisFailedToast: 'Analisis gagal',
    
    // Enhanced error messages
    networkError: 'Koneksi jaringan gagal. Periksa koneksi internet Anda.',
    timeoutError: 'Permintaan timeout. Silakan coba lagi.',
    serverError: 'Terjadi kesalahan server. Silakan coba lagi nanti.',
    rateLimitError: 'Terlalu banyak permintaan. Tunggu sebentar dan coba lagi.',
    apiKeyError: 'Kesalahan konfigurasi layanan. Silakan hubungi dukungan.',
    safetyFilterError: 'Konten ditandai oleh filter keamanan. Coba konten lain.',
    unknownError: 'Terjadi kesalahan tidak terduga. Silakan coba lagi.',
    
    // Retry messages
    retrying: 'Mencoba lagi...',
    retryAttempt: 'Percobaan',
    of: 'dari',
    tryAgain: 'Coba Lagi',
    
    // Export
    exportJson: 'Ekspor JSON',
    exportPdf: 'Ekspor PDF',
    exportSuccess: 'Ekspor berhasil',
    downloadStarted: 'Unduhan dimulai',
    generatedAt: 'Dibuat pada',
    
    // History
    recentAnalyses: 'Analisis Terbaru',
    noHistory: 'Belum ada riwayat analisis',
    viewDetails: 'Lihat Detail',
    clearHistory: 'Hapus Riwayat',
    historyClearedToast: 'Riwayat dihapus',
    analysisRestored: 'Analisis dipulihkan',
    deleteFromHistory: 'Hapus',
    ago: 'yang lalu',
    justNow: 'Baru saja',
    minute: 'menit',
    minutes: 'menit',
    hour: 'jam',
    hours: 'jam',
    day: 'hari',
    days: 'hari',
  },
} as const;

export type TranslationKey = keyof typeof translations.en;
